# Generated by Django 2.2.2 on 2019-06-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuenosAires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contra',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo',
        ),
    ]
