# Generated by Django 2.1.5 on 2019-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuenosAires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contra',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='Pendient', max_length=10, null='true'),
        ),
    ]
