# Generated by Django 2.2.2 on 2019-06-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuenosAires', '0002_auto_20190628_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='Pendient', max_length=10),
        ),
    ]
